services:
  sdr-capture:
    build: .
    container_name: gnuradio-sdr-capture
    volumes:
      - ./src:/app/src
      - ./Makefile:/app/Makefile
      - ./build:/app/build
      - ./package:/app/package
      - ./run:/app/run
      - ./config.cfg:/app/config.cfg
      - ./toGround:/app/toGround
    working_dir: /app
    tty: true
