services:
  pretty-doomed:
    build: .
    container_name: pretty-doomed
    volumes:
      - ./src:/app/src
      - ./tools:/app/tools
      - ../common:/app/common
      - ./tests:/app/tests
      - ./VERSION:/app/VERSION
      - ./Makefile:/app/Makefile
      - ./build/local:/app/build/local
      - ./models:/app/models
      - ./input:/app/input
      - ./ascii.txt:/app/ascii.txt
      - ./config.cfg:/app/config.cfg
      - ./variants.cfg:/app/variants.cfg
      - ./run:/app/run
      - ./toGround:/app/toGround
      - ../doom/src:/app/doom-src
      - ../doom/build:/app/doom-build
      - ../doom/demos:/app/demos
      - ./assets:/app/assets
    working_dir: /app
    tty: true
