services:
  sherpa-onnx:
    build: .
    container_name: sherpa-onnx-sepp
    volumes:
      - ./src:/app/src
      - ./Makefile:/app/Makefile
      - ./build:/app/build
      - ./package:/app/package
      - ./run:/app/run
      - ./toGround:/app/toGround
      - sherpa-onnx-src:/opt/sherpa-onnx-src
    working_dir: /app
    tty: true

volumes:
  sherpa-onnx-src:
