services:
  sdr-loopback:
    build: .
    container_name: gnuradio-sdr-loopback
    volumes:
      - ./src:/app/src
      - ./Makefile:/app/Makefile
      - ./build:/app/build
      - ./package:/app/package
      - ./run:/app/run
      - ./config.cfg:/app/config.cfg
      - ./config.emu.cfg:/app/config.emu.cfg
      - ./toGround:/app/toGround
      - ../../../samples:/app/samples
    working_dir: /app
    tty: true
